name: Publish Docker
on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
     
    - name: TF output to var
      env:
        repo: terraform output ECR_repo_url

    - uses: kciter/aws-ecr-action@master
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: repo
        region: eu-west-2
        tags: latest,${{ github.sha }}
        create_repo: true
